### ISSUE TITLE
[BUG] Extremely Wide Product Results

### ISSUE THREAD

**Issue by KouroshKSH** [KouroshKSH/cs308-project#108]
# Why are the product items so wide?
When the user searches for a product and if the result only contains a few products, they'll occupy the whole screen. It's just bad UI and makes it hard to scroll down to see product info.

## `[OPTIONAL]` To Reproduce
1. Go to landing page.
2. Search for a product.
3. The result is probably a single item (since we don't have much in the DB)
4. That single product has 100% width (screen wise)

## `[OPTIONAL]` Screenshots
I searched for `boot` on "Men" department:

![Image](https://github.com/user-attachments/assets/c5bdb25b-384a-4981-b3e4-92d63899b78e)

![Image](https://github.com/user-attachments/assets/48dfee9b-607b-4a32-8eac-016932808abe)

I had to scroll twice to reach the bottom of the page.

## `[OPTIONAL]` Expected behavior
The product items should occupy a decent space and not change based on how many they are.

**Comment by KouroshKSH** [comment]
# Fix
@ArifSari-maker and @NurAycaIlhan 
I'm sure you guys can later enhance this. But for now, here's my fix and let's just roll with it for the demo. Then do the prettifying after the demo. My changes are in `LandingPage.css` file as the following:

```css
/* Ensure the product grid has a max width and centers items */
.product-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); /* Responsive grid */
    gap: 20px; /* Space between items */
    justify-content: center; /* Center items horizontally */
    max-width: 1200px; /* Limit the grid width */
    margin: 0 auto; /* Center the grid on the page */
    padding: 20px;
}

/* Limit the size of individual product items */
.product-item {
    max-width: 300px; /* Limit the width of each product */
    width: 100%; /* Allow it to shrink if needed */
    border: 1px solid #ccc;
    padding: 10px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    background-color: #fff;
    text-align: center;
}

/* Ensure images fit within the product item */
.product-item img {
    max-width: 100%; /* Ensure the image doesn't overflow */
    height: auto; /* Maintain aspect ratio */
    border-radius: 4px;
}

.product-item:hover {
    transform: translateY(-5px);
    box-shadow: 0 6px 10px rgba(0, 0, 0, 0.15);
}


/*
Sorry for the change from card to item Arif and Ayca, but I'm sure you can fix the UI
*/
```

## Examples
I searched for `boot` on "Men" department, which brings up the only product in a clean way (and doesn't occupy the whole screen):

![Image](https://github.com/user-attachments/assets/895befbe-3386-48ed-b3ba-cb29d2292ce1)

I searched for `f` in "Women" and got 3 results, nicely placed together:

![Image](https://github.com/user-attachments/assets/c087a285-bb11-412d-81a4-62f116846e3c)

I searched for `e` in "Kids" and showed 2 results nicely placed together (good enough):

![Image](https://github.com/user-attachments/assets/499ccdd1-8145-4b9c-afd9-51dbc1715dc6)
